src/Entity/Enum/UserRole.php
<?php

namespace App\Entity\Enum;

use Elao\Enum\Attribute\EnumCase;
use Elao\Enum\ExtrasTrait;
use Elao\Enum\ReadableEnumInterface;
use Elao\Enum\ReadableEnumTrait;

enum UserRole: string implements ReadableEnumInterface
{
    use ReadableEnumTrait;
    use ExtrasTrait;

    #[EnumCase('Super Admin', extras: ['badge_class' => 'bg-primary'])]
    case SUPER_ADMIN = 'ROLE_SUPER_ADMIN';

    #[EnumCase('Admin', extras: ['badge_class' => 'bg-success'])]
    case ADMIN = 'ROLE_ADMIN';

    #[EnumCase('User', extras: ['badge_class' => 'bg-info'])]
    case USER = 'ROLE_USER';

    public function getBadgeClass(): string
    {
        return $this->getExtra('badge_class', true);
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Entity\Enum\UserRole;
use App\Repository\UserRepository;
use Carbon\CarbonImmutable;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;

    #[ORM\Column(length: 255)]
    private string $name;

    #[ORM\Column(length: 255)]
    private string $email;

    #[ORM\Column(length: 255)]
    private string $password;

    #[ORM\Column(options: ['default' => UserRole::USER])]
    private UserRole $role;

    #[ORM\Column]
    private bool $enabled = true;

    #[ORM\Column]
    private bool $enable2fa = true;

    #[ORM\Column]
    private bool $enableBioMetricsFor2fa = true;

    #[ORM\Column]
    private CarbonImmutable $createdAt;

    #[ORM\PrePersist]
    public function prePersist(): void
    {
        $this->createdAt = CarbonImmutable::now();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getRole(): UserRole
    {
        return $this->role;
    }

    public function setRole(UserRole $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function isEnabled(): ?bool
    {
        return $this->enabled;
    }

    public function setEnabled(bool $enabled): static
    {
        $this->enabled = $enabled;

        return $this;
    }

    public function isEnable2fa(): bool
    {
        return $this->enable2fa;
    }

    public function setEnable2fa(bool $enable2fa): static
    {
        $this->enable2fa = $enable2fa;

        return $this;
    }

    public function getCreatedAt(): CarbonImmutable
    {
        return $this->createdAt;
    }


    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): void
    {
        $this->name = $name;
    }

    public function getRoles(): array
    {
        return [$this->role->value];
    }

    public function eraseCredentials(): void
    {
        return;
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function isEnableBioMetricsFor2fa(): bool
    {
        return $this->enableBioMetricsFor2fa;
    }

    public function setEnableBioMetricsFor2fa(bool $enableBioMetricsFor2fa): void
    {
        $this->enableBioMetricsFor2fa = $enableBioMetricsFor2fa;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\Enum\UserRole;
use App\Entity\User;
use Elao\Enum\Bridge\Symfony\Form\Type\EnumType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Name',
                'required' => true
            ])
            ->add('email', EmailType::class, [
                'label' => 'E-mail',
                'required' => true,
            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'invalid_message' => 'The password fields must match.',
                'first_options' => ['label' => 'Password'],
                'second_options' => ['label' => 'Repeat password'],
                'required' => !$options['is_edit_action'],
                'mapped' => false,
            ])
            ->add('role', EnumType::class, [
                'class' => UserRole::class,
                'label' => 'User role',
                'multiple' => false,
            ])
        ;
        if ($options['is_edit_action']) {
            $builder->add('enabled', ChoiceType::class, [
                'label' => 'Enabled',
                'choices' => [
                    'Yes' => true,
                    'No' => false,
                ],
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'is_edit_action' => false,
        ]);
    }
}

src/Controller/UsersController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/users')]
class UsersController extends AbstractController
{
    public function __construct(private readonly UserRepository $userRepository)
    {
    }

    #[Route('/', name: 'users_index')]
    #[IsGranted('ROLE_ADMIN')]
    public function index(Request $request, PaginatorInterface $paginator): Response
    {
        $numberOfRecords = $request->query->getInt('numberOfRecords', 25);
        $users = $paginator->paginate($this->userRepository->createQueryBuilder('u')
            ->getQuery(), $request->query->getInt('page', 1), $numberOfRecords);

        return $this->render('users/index.html.twig', [
            'users' => $users,
            'numberOfRecords' => $numberOfRecords,
        ]);
    }

    #[Route('/new', name: 'users_new')]
    #[IsGranted('ROLE_ADMIN')]
    public function new(Request $request): Response
    {
        $user = new User();
        $userTypeForm = $this->createForm(UserType::class, $user, [
            'is_edit_action' => false
        ]);
        $userTypeForm->handleRequest($request);

        if ($userTypeForm->isSubmitted() && $userTypeForm->isValid()) {
            try {
                $plainPassword = $userTypeForm->get('password')->getData();
                $this->userRepository->saveUser($user, $plainPassword);
                $this->addFlash('success', 'User successfully created.');
                return $this->redirectToRoute('users_index');
            } catch (\Throwable $e) {
                $this->addFlash('danger', $e->getMessage());
                return $this->redirectToRoute('users_index');
            }
        }

        return $this->render('users/new.html.twig', [
            'userTypeForm' => $userTypeForm->createView(),
        ]);
    }

    #[Route('/{id}/edit', name: 'users_edit')]
    #[IsGranted('ROLE_SUPER_ADMIN')]
    public function edit(Request $request, User $user): Response
    {
        $userTypeForm = $this->createForm(UserType::class, $user, [
            'is_edit_action' => true
        ]);
        $userTypeForm->handleRequest($request);

        if ($userTypeForm->isSubmitted() && $userTypeForm->isValid()) {
            try {
                $plainPassword = $userTypeForm->get('password')->getData();
                $this->userRepository->saveUser($user, $plainPassword);
                $this->addFlash('success', 'User successfully updated.');
                return $this->redirectToRoute('users_index');
            } catch (\Throwable $e) {
                $this->addFlash('danger', $e->getMessage());
                return $this->redirectToRoute('users_index');
            }
        }

        return $this->render('users/edit.html.twig', [
            'user' => $user,
            'userTypeForm' => $userTypeForm->createView(),
        ]);
    }

    #[Route('/{id}/delete', name: 'users_delete')]
    #[IsGranted('ROLE_SUPER_ADMIN')]
    public function delete(Request $request, User $user): JsonResponse
    {
        $csrfToken = $request->request->get('_token');
        $status = false;
        $errorMessage = null;
        
        if (!$this->isCsrfTokenValid('delete_user', $csrfToken)) {
            $errorMessage = 'Invalid CSRF token';
        } else {
            try {
                $this->userRepository->remove($user);
                $status = true;
            } catch (\Throwable $e) {
                $errorMessage = 'Failed to delete user, ' . $e->getMessage();
            }
        }

        return $this->json([
            'status' => $status,
            'errorMessage' => $errorMessage
        ]);
    }
}

templates/users/_form.html.twig
{{ form_start(userTypeForm) }}
<div class="row">
    <div class="col-md-4">
        {{ form_row(userTypeForm.name) }}
    </div>
    <div class="col-md-4">
        {{ form_row(userTypeForm.email) }}
    </div>
    <div class="col-md-4">
        {{ form_row(userTypeForm.role) }}
    </div>
    <div class="col-md-4">
        {{ form_row(userTypeForm.password.first) }}
    </div>
    <div class="col-md-4">
        {{ form_row(userTypeForm.password.second) }}
    </div>

    {% if userTypeForm.enabled is defined and userTypeForm.enabled %}
        <div class="col-md-4">
            {{ form_row(userTypeForm.enabled) }}
        </div>
    {% endif %}

    <div class="col-md-12">
        <input type="submit" value="submit" class="btn btn-primary">
    </div>
</div>
{{ form_end(userTypeForm) }}

templates/users/edit.html.twig
{% extends 'base.html.twig' %}
{% set active = 'users' %}
{% block title %} Edit | Users {% endblock %}

{% block body %}
    <div class="card mt-3 mb-2">
        <div class="card-body">
            <h5 class="card-title">Edit User {{ user.name }}</h5>
            {{ include('users/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/users/index.html.twig
{% extends 'base.html.twig' %}
{% set active = 'users' %}
{% block title %} Users {% endblock %}

{% block body %}
    <div class="d-flex justify-content-end">
        <a href="{{ path('users_new') }}" class="btn btn-primary">New User</a>
    </div>
    <div class="card mt-3 mb-2">
        <div class="table-responsive rounded">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th>{{ knp_pagination_sortable(users, 'Id', 'u.id') }}</th>
                    <th>{{ knp_pagination_sortable(users, 'Name', 'u.name') }}</th>
                    <th>E-mail</th>
                    <th>Enabled</th>
                    <th>{{ knp_pagination_sortable(users, 'Role', 'u.role') }}</th>
                    <th>{{ knp_pagination_sortable(users, 'Time Created', 'u.createdTime') }}</th>
                    <th class="text-end">Action</th>
                </tr>
                </thead>
                <tbody class="table-group-divider">
                {% set userRole = enum("\\App\\Entity\\Enum\\UserRole") %}
                {% for user in users %}
                    {% include 'users/row.html.twig' %}
                {% else %}
                    <tr>
                        <td colspan="13">No records found.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <input type="hidden" id="user_delete_csrf" value="{{ csrf_token("delete_user") }}">
        {{ include('paginator/pagination_card_footer.html.twig', {'knp_result_set': users}) }}
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            let deleteUserBtns = document.querySelectorAll('.delete-user-btn');
            deleteUserBtns.forEach(btn => {
                btn.addEventListener('click', (e) => {
                    Swal.fire({
                        title: "Are you sure?",
                        text: "You won't be able to revert this!",
                        icon: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#3085d6",
                        cancelButtonColor: "#d33",
                        confirmButtonText: "Yes, delete it!"
                    }).then((result) => {
                        if (result.isConfirmed) {
                            let csrfToken = document.getElementById('user_delete_csrf').value;
                            let userId = btn.getAttribute('data-user-id');
                            let deleteUserURL = '{{ path('users_delete', {'id': 0}) }}'.replace('0', userId);
                            let formData = new FormData();
                            formData.append('_token', csrfToken);

                            fetch(deleteUserURL, {
                                method: 'POST',
                                body: formData,
                            }).then((res) => {
                                return res.json();
                            }).then(response => {
                                if (response.status) {
                                    btn.closest('tr').remove();
                                    Swal.fire({
                                        title: "Deleted!",
                                        text: "User has been deleted.",
                                        icon: "success"
                                    });
                                } else {
                                    Swal.fire({
                                        title: "Error!",
                                        text: response.errorMessage,
                                        icon: "error"
                                    });
                                }
                            });
                        } else {
                            Swal.fire("Cancelled", "Your user is safe :)", "error");
                        }
                    });
                });
            });
        });
    </script>
{% endblock %}

templates/users/new.html.twig
{% extends 'base.html.twig' %}
{% set active = 'users' %}
{% block title %} New | Users {% endblock %}

{% block body %}
    <div class="card mt-3 mb-2">
        <div class="card-body">
            <h5 class="card-title">New User</h5>
            {{ include('users/_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/users/row.html.twig
<tr>
    <td>{{ user.id }}</td>
    <td>{{ user.name }}</td>
    <td>{{ user.email }}</td>
    <td>
        <span class="badge rounded-pill  text-white bg-{{ user.enabled ? 'success' : 'danger' }}">{{ user.enabled ? 'Yes' : 'No' }}</span>
    </td>
    <td>
        <span class="badge {{ user.role.badgeClass }}">{{ user.role.readable }}</span>
    </td>
    <td>
        {{ user.createdAt|format('Y-m-d H:i:s') }}
    </td>

    <td>
        <a href="{{ path('users_edit', {'id': user.id}) }}" class="text-decoration-none fs-6 text-body" data-bs-toggle="tooltip" data-bs-original-title="Edit">
            <i class="fa fa-pen"></i>
        </a>
        <a href="javascript:void(0)" class="text-decoration-none fs-6 text-danger delete-user-btn" data-user-id="{{ user.id }}" data-email="{{ user.email }}" data-bs-toggle="tooltip" data-bs-original-title="Delete">
            <i class="fa fa-trash"></i>
        </a>
    </td>
</tr>